<html>
  <head>
    
  </head>
  <body><hr><br><p>de : BFTC<br>para : Francis</p><p><b>Assunto : Link para um video</b></p>
    <p style="margin-top: 0">
      Ola Francis, se estiver ai acesse esse link: <a href="https://www.youtube.com/watch?v=JZaChTYV6pU">https://www.youtube.com/watch?v=JZaChTYV6pU 
      </a>
    </p>
    <p style="margin-top: 0">
      Aqui eu falo sobre a <b>Historia</b> <b>da</b> <b>internet</b> e sobre 
      alguns <i>inventores, </i>
    </p>
    <p style="margin-top: 0">
      Espero que goste!
    </p>
    <img src="file:\C:\Users\BFTC_Win7\Desktop\ChatServer\imgs\happy.jpg" width="20" height="20">
    <img src="file:\C:\Users\BFTC_Win7\Desktop\ChatServer\imgs\happy.jpg" width="20" height="20">
  <br><hr></body>
</html>
