<html>
  <head>
    
  </head>
  <body><hr><br><p>de : BFTC<br>para : Francis</p><p><b>Assunto : Estou de volta</b></p>
    <p style="margin-top: 0">
      Agora estou online.. na verdade, eu fui fazer um trabalho.
    </p>
    <p style="margin-top: 0">
      Nossa aprendeu mesmo hein, que bom que gostou!
    </p>
    <img src="file:\C:\Users\BFTC_Win7\Desktop\ChatServer\imgs\smile.jpg" width="20" height="20">
  <br><hr></body>
</html>
