<html>
  <head>
    
  </head>
  <body><hr><br><p>de : Francis<br>para : BFTC</p><p><b>Assunto : Resposta ao video</b></p>
    <p style="margin-top: 0">
      Percebi que voc&#234; n&#227;o est&#225; online! acabei de ver seu video
    </p>
    <img src="file:\C:\Users\BFTC\Downloads\Arquivos\Portifolio BFTC\Meus Softwares [Revisar]\ChatServer\imgs\happy.jpg" width="20" height="20">
    Aprendi muitas coisas sobre a origem do email eletr&#244;nico com ray 
    tomlinsom, O protocolo FTP de abhay bushan e a pr&#243;pria origem da internet 
    que come&#231;ou pelo presidente eisenhower pela <b>DARPA</b> . Irei 
    estudar mais seus videos, muito obrigado!
  <br><hr></body>
</html>
