<html>
  <head>
    
  </head>
  <body><hr><br><p>de : Francis<br>para : BFTC</p><p><b>Assunto : Transferência de arquivo</b></p>
    <p style="margin-top: 0">
      Eu gostaria de enviar um software que eu desenvolvi para controlar uma 
      l&#226;mpada, gostaria de ver?
    </p>
    <img src="file:\C:\Users\BFTC\Downloads\Arquivos\Portifolio BFTC\Meus Softwares [Revisar]\ChatServer\imgs\happy.jpg" width="20" height="20">
  <br><hr></body>
</html>
